# Generated by Django 5.0.3 on 2024-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusotomer_name', models.CharField(max_length=100, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_city', models.CharField(max_length=10, null=True)),
                ('customer_state', models.CharField(max_length=10, null=True)),
                ('customer_country', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
