---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: petcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: registry.deti/petcare/payments:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path:
            port:
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: petcare
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: payments

