
services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - /payments:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paymentsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: .
    # image: payments-web-1
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
    command: .\entrypoint.bat
    volumes:
      - .:/payments   # Mount Django project directory
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
