services:
  db:
    image: sqlite:latest
    volumes:
      - ./db.sqlite3:/var/lib/sqlite/db.sqlite3   # Mount SQLite database file
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/payments   # Mount Django project directory
    ports:
      - "10.139.0.0:8080:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
