openapi: 3.0.3
info:
  title: Payments API
  version: 1.0.0
  description: API for Payments
paths:
  /payment/:
    get:
      operationId: payment_list
      tags:
      - payment
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payments'
          description: ''
    post:
      operationId: payment_create
      tags:
      - payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payments'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payments'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payments'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
  /payment/{cid}/{pid}/:
    get:
      operationId: payment_list_2
      parameters:
      - in: path
        name: cid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: pid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - payment
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payments'
          description: ''
    post:
      operationId: payment_create_2
      parameters:
      - in: path
        name: cid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: pid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payments'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payments'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payments'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
  /payment/{cid}/{pid}/{id}/:
    get:
      operationId: payment_retrieve
      parameters:
      - in: path
        name: cid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      - in: path
        name: pid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - payment
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
    put:
      operationId: payment_update
      parameters:
      - in: path
        name: cid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      - in: path
        name: pid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payments'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payments'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payments'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
    patch:
      operationId: payment_partial_update
      parameters:
      - in: path
        name: cid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      - in: path
        name: pid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPayments'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPayments'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPayments'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
    delete:
      operationId: payment_destroy
      parameters:
      - in: path
        name: cid
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      - in: path
        name: pid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - payment
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /payment/{id}/:
    get:
      operationId: payment_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      tags:
      - payment
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
    put:
      operationId: payment_update_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      tags:
      - payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payments'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payments'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payments'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
    patch:
      operationId: payment_partial_update_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      tags:
      - payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPayments'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPayments'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPayments'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payments'
          description: ''
    delete:
      operationId: payment_destroy_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this payments.
        required: true
      tags:
      - payment
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /payment_complete/:
    patch:
      operationId: payment_complete_partial_update
      description: Endpoint to complete payment by updating payment status
      tags:
      - payment_complete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPaymentComplete'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPaymentComplete'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPaymentComplete'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
        '400':
          content:
            application/json:
              schema:
                error: Invalid JSON data
          description: ''
  /registration/:
    get:
      operationId: registration_list
      tags:
      - registration
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Clients'
          description: ''
    post:
      operationId: registration_create
      tags:
      - registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clients'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Clients'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Clients'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clients'
          description: ''
  /registration/{id}/:
    get:
      operationId: registration_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this clients.
        required: true
      tags:
      - registration
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clients'
          description: ''
components:
  schemas:
    Clients:
      type: object
      properties:
        name:
          type: string
          maxLength: 300
        email:
          type: string
          format: email
          maxLength: 254
        paypal_client_id:
          type: string
          maxLength: 80
        membership_plan:
          $ref: '#/components/schemas/MembershipPlanEnum'
        unique_key:
          type: string
          format: uuid
        state:
          $ref: '#/components/schemas/StateEnum'
      required:
      - email
      - membership_plan
      - name
      - paypal_client_id
    MembershipPlanEnum:
      enum:
      - a
      - b
      - c
      type: string
      description: |-
        * `a` - Standard
        * `b` - Premium
        * `c` - Premium Plus
    PatchedPaymentComplete:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        paid:
          type: boolean
    PatchedPayments:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        client_unique_key:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 120
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        paid:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    Payments:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        client_unique_key:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 120
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        paid:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - amount
      - created_at
      - id
      - name
      - updated_at
    StateEnum:
      enum:
      - a
      - i
      - s
      - w
      type: string
      description: |-
        * `a` - Active
        * `i` - Inactive
        * `s` - Suspended
        * `w` - Awaiting Approval
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
