# Generated by Django 5.0.3 on 2024-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0002_rename_student_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('membership_plan', models.CharField(choices=[('a', 'Standard'), ('b', 'Premium'), ('c', 'Premium Plus')], max_length=1)),
                ('unique_key', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='payments',
            name='gender',
        ),
        migrations.AddField(
            model_name='payments',
            name='type',
            field=models.CharField(blank=True, choices=[('CC', 'Credit Card'), ('P', 'Paypal'), ('O', 'Others')], max_length=5),
        ),
    ]
