# Generated by Django 5.0.4 on 2024-04-16 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0003_clients_remove_payments_gender_payments_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'API Clients'},
        ),
        migrations.RemoveField(
            model_name='payments',
            name='type',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='iban',
            field=models.CharField(default=123456, max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='state',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('s', 'Suspended'), ('w', 'Awaiting Approval')], default='w', max_length=1),
        ),
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='client_unique_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='payments',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='clients',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
