# Generated by Django 5.0.3 on 2024-03-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0003_clients_remove_payments_gender_payments_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'API Clients'},
        ),
        migrations.AddField(
            model_name='clients',
            name='state',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('s', 'Suspended')], default='Inactive', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='client_unique_key',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payments',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
