# Generated by Django 5.0.3 on 2024-03-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0004_alter_clients_options_clients_state_payments_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='state',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('s', 'Suspended')], default='Inactive', max_length=1),
        ),
    ]
