# Generated by Django 5.0.3 on 2024-03-25 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0005_alter_clients_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='id',
        ),
        migrations.AlterField(
            model_name='clients',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
