# Generated by Django 5.0.4 on 2024-04-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0006_alter_payments_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='temp_id',
            new_name='id',
        ),
    ]
