# Generated by Django 5.0.3 on 2024-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0007_clients_id_alter_clients_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='unique_key',
            field=models.CharField(max_length=300),
        ),
    ]
