# Generated by Django 5.0.3 on 2024-03-25 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0009_alter_clients_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='client_unique_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
