# Generated by Django 5.0.3 on 2024-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0010_alter_payments_client_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
