# Generated by Django 5.0.3 on 2024-03-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0011_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='state',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('s', 'Suspended'), ('w', 'Awaiting Approval')], default='Inactive', max_length=1),
        ),
    ]
