# Generated by Django 5.0.3 on 2024-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0013_alter_clients_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
