# Generated by Django 5.0.3 on 2024-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0014_alter_clients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
