# Generated by Django 5.0.3 on 2024-03-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0016_alter_clients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='paypal_client_id',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
