# Generated by Django 5.0.3 on 2024-04-03 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0019_remove_payments_type_payments_payment_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_unique_key',
        ),
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
