# Generated by Django 5.0.3 on 2024-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0020_remove_payments_payment_unique_key_alter_payments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
