# Generated by Django 5.0.3 on 2024-04-03 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0022_alter_payments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
