# Generated by Django 5.0.3 on 2024-04-04 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0023_alter_payments_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='paypal_client_id',
        ),
        migrations.AddField(
            model_name='clients',
            name='iban',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
