# Generated by Django 5.0.3 on 2024-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0025_remove_clients_iban_clients_paypal_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='paypal_client_id',
        ),
        migrations.AddField(
            model_name='clients',
            name='iban',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
    ]
