# Create Booking-api deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-api
  namespace: egs-petcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-api
  template:
    metadata:
      labels:
        app: booking-api
    spec:
      containers:
      - name: booking-api
        image: registry.deti/egs-petcare/booking-api:v3
        resources:
          requests:
            memory: "500Mi"
            cpu: "10m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - containerPort: 8040
        env:
        - name: DATABASE_HOST
          value: "booking-db"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "bookingservice"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "password"
---
## Create Booking-db deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
  namespace: egs-petcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-db
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      containers:
      - name: booking-db
        image: postgres:latest
        env:  # environment variables 
        - name: POSTGRES_DB  
          value: "bookingservice"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data 
      volumes:
      - name: postgres-data
        emptyDir: {}

# Create Service for Booking-api
---
apiVersion: v1
kind: Service
metadata:
  name: booking-api
  namespace: egs-petcare
spec:
  ports:
  - port: 80
    targetPort: 8040
  selector:
    app: booking-api

## Create Service for Booking-db
---
apiVersion: v1
kind: Service
metadata:
  name: booking-db
  namespace: egs-petcare
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: booking-db

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-petcare-k3s
  namespace: egs-petcare
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: booking-petcare.deti
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booking-api
            port: 
              number: 80
