version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: booking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookingservice
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    container_name: booking-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8040:8040'
    depends_on:
      - postgres
    volumes:
      - .:/app
