name: pet_sitter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1
#Database ISAR
isar_version: &isar_version 3.1.0 # define the version to be used

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  logger: ^1.3.0
  path_provider: ^2.0.15
  flutter_local_notifications: ^9.1.6
  blur: ^3.1.0
  dio: ^5.3.3
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  uuid: ^4.3.2
  http: ^0.13.3
  url_launcher: ^6.0.9
  webview_flutter: ^4.0.1
  rive: ^0.13.5
  intl: ^0.18.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  build_runner: any
  pretty_dio_logger: ^1.3.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/check_animation.riv
    - assets/paw.riv
    - assets/cross.riv
    
